baseURL = 'https://kiraa-blog.vercel.app/' # 部署后Vercel会自动分配，先填这个占位
languageCode = 'zh-cn'
title = "Kiraa" # 改成你的博客名
theme = "FixIt" # 核心：指定主题

hasCJKLanguage = true
summaryLength = 200

[params]
  [params.author]
    name = "kiraa"
    avatar = "https://github.com/kcccn.png"
    link = "https://github.com/kcccn"

  [params.page]
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank">CC BY-NC-SA 4.0</a>'

  [params.page.math]
    enable = true
    type = "katex"
  
  # 代码块设置
  [params.page.code]
    maxShownLines = 50 # 长代码折叠
    copy = true        # 允许复制

  [params.app]
    fontFamily = "JetBrains Mono, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"
    iconColor = "#42b883"
    tileColor = "#42b883"

    [params.app.themeColor]
      light = "#42b883"
      dark = "#42b883"

  [params.page.toc]
    enable = true       # ✅ 强制开启
    keepStatic = false  # false = 悬浮在右侧 (Vue/现代文档风格)；true = 固定在文章正文开头
    auto = true         # true = 自动折叠，只显示当前章节

  [params.customPartials]
    head = ["custom/footer-globe-head.html"]
    footer = ["custom/footer-globe.html"]

  [params.page.comment]
    enable = true

    [params.page.comment.giscus]
      enable = true
      repo = "kcccn/kiraa-blog"
      repoId = "R_kgDORC3Ygw"
      category = "Announcements"
      categoryId = "DIC_kwDORC3Yg84C7PuG"
      mapping = "pathname"
      origin = "https://giscus.app"
      strict = "0"
      term = ""
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom"
      lang = "zh-CN"
      lightTheme = "light"
      darkTheme = "dark"
      lazyLoad = true

  [params.footer]
    enable = true
    since = 2026

[markup]
  _merge = "shallow"
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
    style = "monokai"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许在 Markdown 里直接写 HTML (比如 iframe 视频)

    [markup.goldmark.extensions]
      # ⚠️ 注意：这里千万不要加 passthrough = false 这一行，直接留空或者放其他扩展

      [markup.goldmark.extensions.passthrough]
        enable = true
        auto = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[permalinks]
  posts = '/post/:contentbasename/'

[outputs]
  _merge = "shallow"

[taxonomies]
  _merge = "shallow"
