baseURL = 'https://kiraa-blog.vercel.app/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = 'FixIt'

[params]
  # 开启数学公式
  math = true
  
[params.section.math]
  enable = true
  # 推荐使用 KaTeX，渲染速度远超 MathJax
  copyTex = true
  mhchem = true